"""add sponsors table

Revision ID: 1b13e5e48c1e
Revises: b3945b731a7a
Create Date: 2025-08-11 19:32:43.987721

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1b13e5e48c1e"
down_revision: str | Sequence[str] | None = "b3945b731a7a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sponsors",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("logo_path", sa.String(), nullable=False),
        sa.Column("click_url", sa.Text(), nullable=True),
        sa.Column("weight", sa.Integer(), nullable=False),
        sa.Column("surfaces", sa.JSON(), nullable=True),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_sponsors_active_window", "sponsors", ["start_at", "end_at"], unique=False)
    op.create_index("ix_sponsors_weight", "sponsors", ["weight"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_sponsors_weight", table_name="sponsors")
    op.drop_index("ix_sponsors_active_window", table_name="sponsors")
    op.drop_table("sponsors")
    # ### end Alembic commands ###
