"""add PlayerXIREQUEST and PlayerXIResponse fields

Revision ID: 2d0c3e4d3a75
Revises: 4202ae331ef6
Create Date: 2025-08-14 20:48:55.077905

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2d0c3e4d3a75"
down_revision: Union[str, Sequence[str], None] = "4202ae331ef6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
