"""add PlayerXIREQUEST and PlayerXIResponse fields

Revision ID: 2d0c3e4d3a75
Revises: 4202ae331ef6
Create Date: 2025-08-14 20:48:55.077905

"""

from collections.abc import Sequence


# revision identifiers, used by Alembic.
revision: str = "2d0c3e4d3a75"
down_revision: str | Sequence[str] | None = "4202ae331ef6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
