"""Create initial game table

Revision ID: 3d32fa33fe5e
Revises:
Create Date: 2025-07-28 22:06:08.629647

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3d32fa33fe5e"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "games",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("team_a", sa.JSON(), nullable=True),
        sa.Column("team_b", sa.JSON(), nullable=True),
        sa.Column("overs_limit", sa.Integer(), nullable=True),
        sa.Column("toss_winner_team", sa.String(), nullable=True),
        sa.Column("decision", sa.String(), nullable=True),
        sa.Column("batting_team_name", sa.String(), nullable=True),
        sa.Column("bowling_team_name", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("total_runs", sa.Integer(), nullable=True),
        sa.Column("total_wickets", sa.Integer(), nullable=True),
        sa.Column("overs_completed", sa.Integer(), nullable=True),
        sa.Column("balls_this_over", sa.Integer(), nullable=True),
        sa.Column("current_striker_id", sa.String(), nullable=True),
        sa.Column("current_non_striker_id", sa.String(), nullable=True),
        sa.Column("deliveries", sa.JSON(), nullable=True),
        sa.Column("batting_scorecard", sa.JSON(), nullable=True),
        sa.Column("bowling_scorecard", sa.JSON(), nullable=True),
        sa.Column("current_inning", sa.Integer(), nullable=True),
        sa.Column("first_inning_summary", sa.JSON(), nullable=True),
        sa.Column("target", sa.Integer(), nullable=True),
        sa.Column("result", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_games_id"), "games", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_games_id"), table_name="games")
    op.drop_table("games")
    # ### end Alembic commands ###
