"""add sponsor_impressions

Revision ID: 4202ae331ef6
Revises: 1b13e5e48c1e
Create Date: 2025-08-11 22:22:38.377424

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4202ae331ef6"
down_revision: str | Sequence[str] | None = "1b13e5e48c1e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sponsor_impressions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("game_id", sa.String(), nullable=False),
        sa.Column("sponsor_id", sa.String(), nullable=False),
        sa.Column(
            "at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["sponsor_id"], ["sponsors.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_sponsor_impressions_at", "sponsor_impressions", ["at"], unique=False)
    op.create_index(
        op.f("ix_sponsor_impressions_game_id"),
        "sponsor_impressions",
        ["game_id"],
        unique=False,
    )
    op.create_index(
        "ix_sponsor_impressions_sponsor_id",
        "sponsor_impressions",
        ["sponsor_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_sponsor_impressions_sponsor_id", table_name="sponsor_impressions")
    op.drop_index(op.f("ix_sponsor_impressions_game_id"), table_name="sponsor_impressions")
    op.drop_index("ix_sponsor_impressions_at", table_name="sponsor_impressions")
    op.drop_table("sponsor_impressions")
    # ### end Alembic commands ###
