"""add required_run_rate to games

Revision ID: 4d3b902edbe8
Revises: d2bd42f8d9e8
Create Date: 2025-10-27 00:43:05.721084

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4d3b902edbe8"
down_revision: str | Sequence[str] | None = "d2bd42f8d9e8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("games", sa.Column("required_run_rate", sa.Float(), nullable=True))
    op.alter_column(
        "games",
        "team_a",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        nullable=False,
    )
    op.alter_column(
        "games",
        "team_b",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        nullable=False,
    )
    op.alter_column("games", "dls_enabled", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column(
        "games",
        "interruptions",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column("games", "total_runs", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "games", "total_wickets", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "games", "overs_completed", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "games", "balls_this_over", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "games",
        "extras_totals",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=None,
        type_=sa.JSON(),
        existing_nullable=False,
    )
    op.alter_column(
        "games",
        "fall_of_wickets",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=None,
        type_=sa.JSON(),
        existing_nullable=False,
    )
    op.alter_column(
        "games",
        "phases",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=None,
        type_=sa.JSON(),
        existing_nullable=False,
    )
    op.alter_column(
        "games",
        "projections",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=None,
        type_=sa.JSON(),
        existing_nullable=False,
    )
    op.alter_column(
        "games",
        "deliveries",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        nullable=False,
    )
    op.alter_column(
        "games",
        "batting_scorecard",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        nullable=False,
    )
    op.alter_column(
        "games",
        "bowling_scorecard",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        nullable=False,
    )
    op.alter_column(
        "games", "current_inning", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "games", "current_inning", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "games",
        "bowling_scorecard",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "games",
        "batting_scorecard",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "games",
        "deliveries",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "games",
        "projections",
        existing_type=sa.JSON(),
        server_default=sa.text("'{}'::jsonb"),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.alter_column(
        "games",
        "phases",
        existing_type=sa.JSON(),
        server_default=sa.text("'{}'::jsonb"),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.alter_column(
        "games",
        "fall_of_wickets",
        existing_type=sa.JSON(),
        server_default=sa.text("'[]'::jsonb"),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.alter_column(
        "games",
        "extras_totals",
        existing_type=sa.JSON(),
        server_default=sa.text("'{}'::jsonb"),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.alter_column(
        "games", "balls_this_over", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "games", "overs_completed", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column("games", "total_wickets", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("games", "total_runs", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "games",
        "interruptions",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column("games", "dls_enabled", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column(
        "games",
        "team_b",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "games",
        "team_a",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.drop_column("games", "required_run_rate")
    # ### end Alembic commands ###
