"""add overs_per_day setup fields

Revision ID: 598a9558c298
Revises: c7cb4087a1c1
Create Date: 2025-08-09 17:04:28.438445

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "598a9558c298"
down_revision: Union[str, Sequence[str], None] = "c7cb4087a1c1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("games", sa.Column("overs_per_day", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("games", "overs_per_day")
    # ### end Alembic commands ###
