"""team roles + game_contributors

Revision ID: b3945b731a7a
Revises: 598a9558c298
Create Date: 2025-08-11 12:23:43.505246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3945b731a7a'
down_revision: Union[str, Sequence[str], None] = '598a9558c298'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_contributors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('role', sa.Enum('scorer', 'commentary', 'analytics', name='game_contributor_role'), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_contributors_game_id'), 'game_contributors', ['game_id'], unique=False)
    op.create_index('ix_game_contributors_unique', 'game_contributors', ['game_id', 'user_id', 'role'], unique=True)
    op.add_column('games', sa.Column('team_a_captain_id', sa.Text(), nullable=True))
    op.add_column('games', sa.Column('team_a_keeper_id', sa.Text(), nullable=True))
    op.add_column('games', sa.Column('team_b_captain_id', sa.Text(), nullable=True))
    op.add_column('games', sa.Column('team_b_keeper_id', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'team_b_keeper_id')
    op.drop_column('games', 'team_b_captain_id')
    op.drop_column('games', 'team_a_keeper_id')
    op.drop_column('games', 'team_a_captain_id')
    op.drop_index('ix_game_contributors_unique', table_name='game_contributors')
    op.drop_index(op.f('ix_game_contributors_game_id'), table_name='game_contributors')
    op.drop_table('game_contributors')
    # ### end Alembic commands ###



