"""add match setup fields

Revision ID: c7cb4087a1c1
Revises: 3d32fa33fe5e
Create Date: 2025-08-09 16:52:27.428426

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c7cb4087a1c1"
down_revision: str | Sequence[str] | None = "3d32fa33fe5e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("games", sa.Column("match_type", sa.String(), nullable=False))
    op.add_column("games", sa.Column("days_limit", sa.Integer(), nullable=True))
    op.add_column("games", sa.Column("dls_enabled", sa.Boolean(), nullable=True))
    op.add_column("games", sa.Column("interruptions", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("games", "interruptions")
    op.drop_column("games", "dls_enabled")
    op.drop_column("games", "days_limit")
    op.drop_column("games", "match_type")
    # ### end Alembic commands ###
